<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\QuranSura;

class QuranSuraSeeder extends Seeder
{
    public function run(): void
    {
        $suras = [
            // id, name_ar, name_en, ayah_count, is_active
            [1, 'الفاتحة', 'Al-Fatihah', 7, true],
            [2, 'البقرة', 'Al-Baqarah', 286, true],
            [3, 'آل عمران', 'Aal-E-Imran', 200, true],
            [4, 'النساء', 'An-Nisa', 176, true],
            [5, 'المائدة', "Al-Ma'idah", 120, true],
            [6, 'الأنعام', "Al-An'am", 165, true],
            [7, 'الأعراف', "Al-A'raf", 206, true],
            [8, 'الأنفال', 'Al-Anfal', 75, true],
            [9, 'التوبة', 'At-Tawbah', 129, true],
            [10, 'يونس', 'Yunus', 109, true],
            [11, 'هود', 'Hud', 123, true],
            [12, 'يوسف', 'Yusuf', 111, true],
            [13, 'الرعد', "Ar-Ra'd", 43, true],
            [14, 'إبراهيم', 'Ibrahim', 52, true],
            [15, 'الحجر', 'Al-Hijr', 99, true],
            [16, 'النحل', 'An-Nahl', 128, true],
            [17, 'الإسراء', 'Al-Isra', 111, true],
            [18, 'الكهف', 'Al-Kahf', 110, true],
            [19, 'مريم', 'Maryam', 98, true],
            [20, 'طه', 'Ta-Ha', 135, true],
            [21, 'الأنبياء', 'Al-Anbiya', 112, true],
            [22, 'الحج', 'Al-Hajj', 78, true],
            [23, 'المؤمنون', "Al-Mu'minun", 118, true],
            [24, 'النور', 'An-Nur', 64, true],
            [25, 'الفرقان', 'Al-Furqan', 77, true],
            [26, 'الشعراء', "Ash-Shu'ara", 227, true],
            [27, 'النمل', 'An-Naml', 93, true],
            [28, 'القصص', 'Al-Qasas', 88, true],
            [29, 'العنكبوت', 'Al-Ankabut', 69, true],
            [30, 'الروم', 'Ar-Rum', 60, true],
            [31, 'لقمان', 'Luqman', 34, true],
            [32, 'السجدة', 'As-Sajda', 30, true],
            [33, 'الأحزاب', 'Al-Ahzab', 73, true],
            [34, 'سبأ', 'Saba', 54, true],
            [35, 'فاطر', 'Fatir', 45, true],
            [36, 'يس', 'Ya-Sin', 83, true],
            [37, 'الصافات', 'As-Saffat', 182, true],
            [38, 'ص', 'Sad', 88, true],
            [39, 'الزمر', 'Az-Zumar', 75, true],
            [40, 'غافر', 'Ghafir', 85, true],
            [41, 'فصلت', 'Fussilat', 54, true],
            [42, 'الشورى', 'Ash-Shura', 53, true],
            [43, 'الزخرف', 'Az-Zukhruf', 89, true],
            [44, 'الدخان', 'Ad-Dukhan', 59, true],
            [45, 'الجاثية', 'Al-Jathiya', 37, true],
            [46, 'الأحقاف', 'Al-Ahqaf', 35, true],
            [47, 'محمد', 'Muhammad', 38, true],
            [48, 'الفتح', 'Al-Fath', 29, true],
            [49, 'الحجرات', 'Al-Hujurat', 18, true],
            [50, 'ق', 'Qaf', 45, true],
            [51, 'الذاريات', 'Adh-Dhariyat', 60, true],
            [52, 'الطور', 'At-Tur', 49, true],
            [53, 'النجم', 'An-Najm', 62, true],
            [54, 'القمر', 'Al-Qamar', 55, true],
            [55, 'الرحمن', 'Ar-Rahman', 78, true],
            [56, 'الواقعة', 'Al-Waqia', 96, true],
            [57, 'الحديد', 'Al-Hadid', 29, true],
            [58, 'المجادلة', 'Al-Mujadila', 22, true],
            [59, 'الحشر', 'Al-Hashr', 24, true],
            [60, 'الممتحنة', 'Al-Mumtahina', 13, true],
            [61, 'الصف', 'As-Saff', 14, true],
            [62, 'الجمعة', 'Al-Jumua', 11, true],
            [63, 'المنافقون', 'Al-Munafiqun', 11, true],
            [64, 'التغابن', 'At-Taghabun', 18, true],
            [65, 'الطلاق', 'At-Talaq', 12, true],
            [66, 'التحريم', 'At-Tahrim', 12, true],
            [67, 'الملك', 'Al-Mulk', 30, true],
            [68, 'القلم', 'Al-Qalam', 52, true],
            [69, 'الحاقة', 'Al-Haqqa', 52, true],
            [70, 'المعارج', 'Al-Maarij', 44, true],
            [71, 'نوح', 'Nuh', 28, true],
            [72, 'الجن', 'Al-Jinn', 28, true],
            [73, 'المزمل', 'Al-Muzzammil', 20, true],
            [74, 'المدثر', 'Al-Muddathir', 56, true],
            [75, 'القيامة', 'Al-Qiyama', 40, true],
            [76, 'الإنسان', 'Al-Insan', 31, true],
            [77, 'المرسلات', 'Al-Mursalat', 50, true],
            [78, 'النبأ', 'An-Naba', 40, true],
            [79, 'النازعات', "An-Nazi'at", 46, true],
            [80, 'عبس', 'Abasa', 42, true],
            [81, 'التكوير', 'At-Takwir', 29, true],
            [82, 'الانفطار', 'Al-Infitar', 19, true],
            [83, 'المطففين', 'Al-Mutaffifin', 36, true],
            [84, 'الانشقاق', 'Al-Inshiqaq', 25, true],
            [85, 'البروج', 'Al-Buruj', 22, true],
            [86, 'الطارق', 'At-Tariq', 17, true],
            [87, 'الأعلى', 'Al-Ala', 19, true],
            [88, 'الغاشية', 'Al-Ghashiya', 26, true],
            [89, 'الفجر', 'Al-Fajr', 30, true],
            [90, 'البلد', 'Al-Balad', 20, true],
            [91, 'الشمس', 'Ash-Shams', 15, true],
            [92, 'الليل', 'Al-Lail', 21, true],
            [93, 'الضحى', 'Ad-Duha', 11, true],
            [94, 'الشرح', 'Ash-Sharh', 8, true],
            [95, 'التين', 'At-Tin', 8, true],
            [96, 'العلق', 'Al-Alaq', 19, true],
            [97, 'القدر', 'Al-Qadr', 5, true],
            [98, 'البينة', 'Al-Bayyina', 8, true],
            [99, 'الزلزلة', 'Az-Zalzalah', 8, true],
            [100, 'العاديات', 'Al-Adiyat', 11, true],
            [101, 'القارعة', 'Al-Qaria', 11, true],
            [102, 'التكاثر', 'At-Takathur', 8, true],
            [103, 'العصر', 'Al-Asr', 3, true],
            [104, 'الهمزة', 'Al-Humazah', 9, true],
            [105, 'الفيل', 'Al-Fil', 5, true],
            [106, 'قريش', 'Quraish', 4, true],
            [107, 'الماعون', 'Al-Maun', 7, true],
            [108, 'الكوثر', 'Al-Kawthar', 3, true],
            [109, 'الكافرون', 'Al-Kafiroon', 6, true],
            [110, 'النصر', 'An-Nasr', 3, true],
            [111, 'المسد', 'Al-Masad', 5, true],
            [112, 'الإخلاص', 'Al-Ikhlas', 4, true],
            [113, 'الفلق', 'Al-Falaq', 5, true],
            [114, 'الناس', 'An-Nas', 6, true],
        ];

        foreach ($suras as $sura) {
            QuranSura::create([
                'id' => $sura[0],
                'name_ar' => $sura[1],
                'name_en' => $sura[2],
                'ayah_count' => $sura[3],
                'is_active' => $sura[4],
            ]);
        }
    }
}
